// ORBIT desktop shell - one crate, five Windows apps.
//
// Which app this binary becomes is decided at BUILD time by ORBIT_SURFACE,
// which build.rs resolves against desktop/surfaces.json. Nothing about the
// surface is decided at run time, so an exe cannot be mistaken for another.
//
// Air-gapped posture, enforced here:
//   * no updater plugin, no update endpoint, no telemetry, no analytics;
//   * no remote origin - the payload is embedded in the exe and served from
//     the in-process orbit:// scheme;
//   * the "devtools" Cargo feature is not enabled, so release builds have no
//     developer tools;
//   * a Content-Security-Policy is set on the payload response whose whole job
//     is to stop the page reaching anything except the map tile server.

#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

mod native;

use std::io::Read;

// Generated by build.rs. Defines SURFACE_KEY, PRODUCT_NAME, APP_TITLE,
// APP_VERSION, PAYLOAD_STAMP, PAYLOAD_SOURCE, PAYLOAD_RAW_LEN,
// PAYLOAD_IS_PLACEHOLDER, WIN_WIDTH, WIN_HEIGHT, MIN_WIDTH, MIN_HEIGHT.
include!(concat!(env!("OUT_DIR"), "/surface.rs"));

static PAYLOAD_GZ: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/payload.gz"));

// THE NETWORK DECISION: Personal Network permits only the Supabase auth origin
// in addition to the local Tauri bridge. No general remote origin is allowed.
//
// Project rule says the ONE permitted runtime call anywhere in ORBIT is the
// Leaflet/MapLibre basemap tile server. It does not follow that these five exes
// should permit it, and they must not. Evidence, not preference:
//
//   * src/analyse/basemaps.js mode() returns "outline" whenever
//     window.ORBIT_OFFLINE_BUILD === true (basemaps.js:47-54).
//   * BOTH emitters set that flag unconditionally on every payload these exes
//     embed - standalone/build-offline.mjs:341 and build-surface.mjs:487.
//   * So all six artefacts already resolve to the offline outline basemap and
//     never construct a tiles.openfreemap.org URL at all.
//
// Allowing the host here would therefore grant exactly nothing today, while
// leaving a live outbound hole for the day someone changes that flag. It is also
// unreachable in practice: each payload carries its own meta CSP with
// connect-src 'none', and a meta policy and a header policy compose by
// INTERSECTION - the header can never loosen the meta tag.
//
// The comment this replaced described the tile host as "the only permitted
// runtime network call" and allowed it. That was the general product rule
// applied to a build the rule does not reach. Air-gapped estate, OFFICIAL case
// material, a basemap the app is not even asking for: deny it.
//
// If an online basemap is ever wanted on the desktop, that is a deliberate
// decision for Ben, and it takes THREE changes, not one: the emitter must stop
// setting ORBIT_OFFLINE_BUILD, the payload's own meta CSP must permit the host,
// and this constant must too. Needing all three is the point.
//
// 'unsafe-inline' and 'unsafe-eval' stay: the payload is one self-contained HTML
// document built entirely from inline script and style. Be clear-eyed about what
// this policy is - an ANTI-EXFILTRATION control, not an anti-XSS one. Escaping
// imported and pasted data remains the web lane's job.
const DEFAULT_CSP: &str = "default-src 'none'; \
script-src 'self' 'unsafe-inline' 'unsafe-eval' blob: data:; \
style-src 'self' 'unsafe-inline' data:; \
img-src 'self' data: blob:; \
font-src 'self' data:; \
media-src 'self' data: blob:; \
worker-src 'self' blob:; \
child-src 'self' blob:; \
connect-src 'self' data: blob: ipc: http://ipc.localhost https://vjhahnnulqiouthqovdi.supabase.co wss://vjhahnnulqiouthqovdi.supabase.co https://people.googleapis.com; \
form-action 'self' https://vjhahnnulqiouthqovdi.supabase.co; object-src 'none'; base-uri 'self'; frame-ancestors 'none'";

// The IPC origin, and NOTHING else, that the payload's own meta CSP must permit
// or the native bridge is dead. See patch_payload_csp below.
const IPC_CONNECT_SRC: &str = "connect-src 'self' data: blob: ipc: http://ipc.localhost https://vjhahnnulqiouthqovdi.supabase.co wss://vjhahnnulqiouthqovdi.supabase.co https://people.googleapis.com";

fn csp() -> Option<String> {
    match std::env::var("ORBIT_CSP") {
        Ok(v) if v.eq_ignore_ascii_case("off") => None,
        Ok(v) if !v.trim().is_empty() => Some(v),
        _ => Some(DEFAULT_CSP.to_string()),
    }
}

// ---------------------------------------------------------------------------
// Keeping the native bridge alive through the payload's own CSP.
// ---------------------------------------------------------------------------
// Every payload these exes embed carries its own meta CSP containing exactly
// `connect-src 'none'` (standalone/build-offline.mjs:333, build-surface.mjs:483).
// That is the right policy for the file:// browser build, where there is no IPC.
// Inside the shell it is a problem: a meta CSP and a response-header CSP compose
// by INTERSECTION, so `connect-src 'none'` wins over anything this shell sends,
// and if the Tauri IPC transport on WebView2 uses fetch() to http://ipc.localhost
// then every native call fails. The symptom would be "saving does not work",
// which is a long way from the cause.
//
// So: rewrite that ONE directive, in memory, at decompress time. Narrow on
// purpose - `'none'` becomes the IPC origin and nothing else. No remote host is
// added, so the anti-exfiltration property of the original policy is unchanged.
//
//   * The file on disk is NEVER modified. This touches the decompressed copy the
//     shell serves. standalone/*.html and the browser build are untouched, and
//     the build stamp is untouched.
//   * Only an exact `connect-src 'none'` is replaced, and only inside a
//     <meta http-equiv="Content-Security-Policy"> tag. If the emitter changes
//     that string, this becomes a no-op rather than a silent mangling, and
//     __ORBIT_INFO__ / the shim's ipcReady probe will say the bridge is dead.
//   * Set ORBIT_PAYLOAD_CSP_PATCH=off to skip it. Use that to find out whether
//     the patch is needed at all on your Tauri version: if the bridge works with
//     it off, WebView2 is using postMessage rather than fetch, and this can be
//     deleted. That test has NOT been run - see README section 8.
fn patch_payload_csp(html: &mut String) -> bool {
    if std::env::var("ORBIT_PAYLOAD_CSP_PATCH")
        .map(|v| v.eq_ignore_ascii_case("off"))
        .unwrap_or(false)
    {
        return false;
    }
    // Bound the search to the head: the string could otherwise appear in case data.
    let scan_to = html.len().min(1_048_576);
    let head = &html[..scan_to];
    let meta = match head.find("http-equiv=\"Content-Security-Policy\"") {
        Some(i) => i,
        None => return false,
    };
    let end = match head[meta..].find('>') {
        Some(i) => meta + i,
        None => return false,
    };
    let needle = "connect-src 'none'";
    let at = match head[meta..end].find(needle) {
        Some(i) => meta + i,
        None => return false,
    };
    html.replace_range(at..at + needle.len(), IPC_CONNECT_SRC);
    true
}

// Whether the patch actually fired. Surfaced as a response header rather than in
// __ORBIT_INFO__, because reading it there would force the 41 MB decompress
// before the window opens. The authoritative answer to "is the bridge alive" is
// the shim's own ipcReady probe, which measures it instead of inferring it.
static PATCH_APPLIED: std::sync::atomic::AtomicBool = std::sync::atomic::AtomicBool::new(false);

fn payload_html() -> &'static Vec<u8> {
    static CELL: std::sync::OnceLock<Vec<u8>> = std::sync::OnceLock::new();
    CELL.get_or_init(|| {
        let mut out = Vec::with_capacity(PAYLOAD_RAW_LEN + 1024);
        let mut dec = flate2::read::GzDecoder::new(PAYLOAD_GZ);
        // Deliberately NOT `match dec.read_to_end(&mut out)`: the arms move `out`,
        // and a `&mut` borrow taken in a match scrutinee lives to the end of the
        // match. Binding the result first ends the borrow on this line.
        let read = dec.read_to_end(&mut out);
        match read {
            Ok(_) => {
                // The payload is UTF-8 HTML. If it somehow is not, serve it
                // unpatched rather than losing bytes to a lossy conversion.
                match String::from_utf8(out) {
                    Ok(mut s) => {
                        let applied = patch_payload_csp(&mut s);
                        PATCH_APPLIED.store(applied, std::sync::atomic::Ordering::Relaxed);
                        s.into_bytes()
                    }
                    Err(e) => e.into_bytes(),
                }
            }
            Err(e) => format!(
                "<!doctype html><meta charset=\"utf-8\"><title>ORBIT</title>\
                 <body style=\"margin:0;background:#0c1117;color:#e8b34b;font:14px system-ui\">\
                 <div style=\"padding:32px\"><h1 style=\"font-size:18px\">ORBIT payload failed to decompress</h1>\
                 <pre>{}</pre></div>",
                e
            )
            .into_bytes(),
        }
    })
}

fn serve(path: &str) -> tauri::http::Response<Vec<u8>> {
    let builder = tauri::http::Response::builder();
    if path.is_empty() || path == "/" || path == "/index.html" {
        let mut b = builder
            .status(200)
            .header("Content-Type", "text/html; charset=utf-8")
            .header("Cache-Control", "no-store")
            .header("X-Content-Type-Options", "nosniff")
            .header("Referrer-Policy", "no-referrer");
        if let Some(p) = csp() {
            b = b.header("Content-Security-Policy", p);
        }
        // Force the decompress (and therefore the meta-CSP patch) before reading
        // the flag, so the header reports this response and not the previous one.
        let body = payload_html().clone();
        b = b.header(
            "X-ORBIT-Meta-CSP-Patch",
            if PATCH_APPLIED.load(std::sync::atomic::Ordering::Relaxed) {
                "applied"
            } else {
                "absent"
            },
        );
        b.body(body).expect("ORBIT: failed to build payload response")
    } else {
        builder
            .status(404)
            .header("Content-Type", "text/plain; charset=utf-8")
            .body(b"ORBIT: not found. The payload is a single self-contained document.".to_vec())
            .expect("ORBIT: failed to build 404 response")
    }
}

#[cfg(not(mobile))]
pub fn run() {
    let args: Vec<String> = std::env::args().collect();

    // --print-stamp / --stamp-file <path>
    // These exist for the six-artefact build-stamp guard. A GUI-subsystem exe on
    // Windows has no console, so --stamp-file is the reliable form.
    if args.iter().any(|a| a == "--print-stamp") || args.iter().any(|a| a == "--stamp-file") {
        let line = format!("{}\t{}\t{}", SURFACE_KEY, PRODUCT_NAME, PAYLOAD_STAMP);
        if let Some(i) = args.iter().position(|a| a == "--stamp-file") {
            if let Some(p) = args.get(i + 1) {
                let _ = std::fs::write(p, format!("{}\n", line));
            }
        }
        println!("{}", line);
        return;
    }

    if args.iter().any(|a| a == "--help" || a == "-h") {
        println!(
            "{} {} (shell {})\n\
             \n\
             Usage: {}.exe [options]\n\
             \n\
             --case <path>          use this case file instead of the default\n\
             --print-stamp          print \"surface<TAB>product<TAB>buildStamp\" and exit\n\
             --stamp-file <path>    write that same line to a file and exit\n\
             --help                 this text\n\
             \n\
             Environment:\n\
             ORBIT_DATA_DIR         override %APPDATA%\\ORBIT\n\
             ORBIT_CASE_FILE        override the case file path\n\
             ORBIT_WEBVIEW_ISOLATE  1 = do not share the WebView2 profile with the other ORBIT apps\n\
             ORBIT_CSP              off = disable the payload Content-Security-Policy (diagnostics)\n\
             ORBIT_PAYLOAD_CSP_PATCH off = do not widen the payload's own meta CSP\n\
                                    connect-src for the Tauri IPC origin (diagnostics)\n",
            PRODUCT_NAME, PAYLOAD_STAMP, APP_VERSION, PRODUCT_NAME
        );
        return;
    }

    run_app();
}

#[cfg(mobile)]
#[tauri::mobile_entry_point]
pub fn run() {
    tauri::Builder::default()
        .run(tauri::generate_context!())
        .expect("error while running ORBIT mobile application");
}

#[cfg(not(mobile))]
fn run_app() {
    let result = tauri::Builder::default()
        .manage(native::Native::default())
        .invoke_handler(tauri::generate_handler![
            native::case_file_path,
            native::read_case,
            native::write_case,
            native::acquire_lock,
            native::release_lock,
            native::force_lock,
            native::lock_holder
        ])
        .register_uri_scheme_protocol("orbit", |_ctx, request| {
            let path = request.uri().path().to_string();
            serve(&path)
        })
        .setup(|app| {
            build_main_window(app)?;
            native::start_poller(app.handle().clone());
            Ok(())
        })
        .run(tauri::generate_context!());

    if let Err(e) = result {
        fatal(&format!("failed to start: {}", e));
    }
}

#[cfg(not(mobile))]
fn build_main_window(app: &tauri::App) -> Result<(), Box<dyn std::error::Error>> {
    let st = native::load_window_state();

    let mut b = tauri::WebviewWindowBuilder::new(
        app,
        "main",
        tauri::WebviewUrl::CustomProtocol("orbit://localhost/index.html".parse()?),
    )
    .title(APP_TITLE)
    .inner_size(st.width, st.height)
    .min_inner_size(MIN_WIDTH, MIN_HEIGHT)
    .resizable(true)
    .visible(true)
    .initialization_script(native::info_script().as_str())
    .initialization_script(include_str!("shim.js"));

    if let (Some(x), Some(y)) = (st.x, st.y) {
        b = b.position(x, y);
    }

    // Shared WebView2 profile: all five apps use the same origin
    // (http://orbit.localhost) AND the same user-data folder, so localStorage
    // and IndexedDB are one store across ORBIT.exe and the four surface apps.
    // Set ORBIT_WEBVIEW_ISOLATE=1 to opt out.
    #[cfg(windows)]
    {
        b = b.data_directory(native::webview_data_dir());
    }

    let win = b.build()?;
    if st.maximized {
        let _ = win.maximize();
    }
    native::attach_window_hooks(&win);
    Ok(())
}

// A GUI-subsystem binary that dies silently is unusable in the field. Leave a
// breadcrumb the analyst (or Ben) can send back.
#[cfg(not(mobile))]
fn fatal(msg: &str) {
    let line = format!("{} {} - {}\n", PRODUCT_NAME, PAYLOAD_STAMP, msg);
    let p = native::orbit_dir().join("shell-error.log");
    if let Some(d) = p.parent() {
        let _ = std::fs::create_dir_all(d);
    }
    use std::io::Write as _;
    if let Ok(mut f) = std::fs::OpenOptions::new().create(true).append(true).open(&p) {
        let _ = f.write_all(line.as_bytes());
    }
    eprintln!("{}", line);
    std::process::exit(1);
}
